services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ee_user
      POSTGRES_PASSWORD: ee_pass
      POSTGRES_DB: ee_review
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ee_review:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - postgres

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http --domain=live-kiwi-gratefully.ngrok-free.app ee_review:8000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    env_file:
      - .env
    depends_on:
      - ee_review

volumes:
  postgres_data:
